[project]
name = "gold-ai"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "affan  qureshi", email = "affanq243@gmail.com" }
]
requires-python = ">=3.12,<3.13"
dependencies = [
    "chromadb>=1.5.9",
    "fastapi>=0.141.1",
    "google-genai>=2.23.0",
    "gunicorn>=23.0.0",
    "langchain-chroma>=1.1.0",
    "langchain-community>=0.4.2",
    "langchain-core>=1.6.1",
    "langchain-groq>=1.1.3",
    "langchain-text-splitters>=1.1.2",
    "langchain>=0.2.5",
    "python-dotenv>=1.2.3",
    "requests>=2.34.2",
    "tavily-python>=0.8.0",
    "uvicorn[standard]>=0.52.4",
]

[project.scripts]
gold-ai = "gold_ai:main"

[build-system]
requires = ["uv_build>=0.12.9,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "httpx>=0.28.1",
    "pytest>=9.1.1",
]
